app_materials/urls.py
from django.urls import path
from .views import material_edit, materials_list, material_create, material_delete

app_name = 'materials'

urlpatterns = [
    path('', materials_list, name='materials_list'),
    path('create/', material_create, name='materials_create'),
    path('edit/<int:id>/', material_edit, name='material_edit'),
    path('delete/<int:id>/', material_delete, name='material_delete'),
]

erp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_users.urls')),
    path('', include('app_core.urls')),
    path('materials/', include(('app_materials.urls'), namespace='materials')),
    path('suppliers/', include(('app_suppliers.urls'), namespace='suppliers')),
]

app_materials/models.py
from django.conf import settings
from django.db import models

class Material(models.Model):
    id_material = models.CharField(max_length=50, null=True, unique=True, verbose_name="Material ID")
    name = models.CharField(max_length=100, verbose_name="Name")
    description = models.TextField(max_length=250, blank=True, verbose_name="Description")
    unit = models.CharField(max_length=50, verbose_name="Unit measure")
    material_type = models.CharField(max_length=50, verbose_name="Material type")
    status = models.CharField(max_length=50, verbose_name="Status")

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Created by", related_name="materials_created") # Usuario que este logueado y que creó el registro, se usa SET_NULL para no eliminar el material si el usuario es eliminado, y se completará automaticamente al crear el registro
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Updated by", related_name="materials_updated") # Usuario que este logueado y que actualizó el registro
    class Meta:
        db_table = 'materials'
        verbose_name = 'Material'
        verbose_name_plural = 'Materials'
        ordering = ['name']

    def __str__(self):
        return self.name

app_materials/forms.py
from django import forms
from app_materials.models import Material

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['id_material','name', 'description', 'unit', 'material_type','status']

app_materials/views.py
from django.shortcuts import get_object_or_404, redirect, render, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
import csv
from django.db import models
from app_users.models import UserRole
from app_materials.models import Material
from .forms import MaterialForm

@login_required
def materials_list(request):

    max_permission = UserRole.objects.filter(user_id=request.user).aggregate(max_permission=models.Max('role__materials'))['max_permission'] or 0

    if max_permission == 0:
        return redirect('dashboard')  # Página de no permiso si el usuario no tiene acceso para ver materiales
   
    # Lógica para obtener la lista de materiales
    materials_list = Material.objects.all()
    
    id_material = request.GET.get('id_material')
    name = request.GET.get('name')
    material_type = request.GET.get('material_type')
    status = request.GET.get('status')

    if id_material:
        materials_list = materials_list.filter(id_material__icontains=id_material)
    if name:
        materials_list = materials_list.filter(name__icontains=name)
    if material_type:
        materials_list = materials_list.filter(material_type__icontains=material_type)
    if status is not None and status != '':
        materials_list = materials_list.filter(status=status)

    # Exportar a CSV si se solicita
    if request.GET.get('export') == 'csv':
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="materials.csv"'
        response.write('\ufeff'.encode('utf8'))  # BOM para Excel

        writer = csv.writer(response)
        writer.writerow(['ID Material', 'Name', 'Description', 'Unit', 'Material Type', 'Status', 'Created By', 'Created At', 'Updated At'])

        for material in materials_list:
            writer.writerow([
                material.id_material, 
                material.name, 
                material.description, 
                material.unit, 
                material.material_type, 
                material.status, 
                material.created_by.username if material.created_by else 'N/A', 
                material.created_at.strftime('%Y-%m-%d %H:%M:%S'), 
                material.updated_at.strftime('%Y-%m-%d %H:%M:%S')])
        return response

    paginator = Paginator(materials_list, 10)  # 10 materiales por página
    page_number = request.GET.get('page')
    pag_obj = paginator.get_page(page_number)

    return render(request, 'materials/material_list.html', {'pag_obj': pag_obj})

def material_create(request):
    max_permission = UserRole.objects.filter(user_id=request.user).aggregate(max_permission=models.Max('role__materials'))['max_permission'] or 0

    # Verificamos si el usuario tiene permiso para crear o modificar materiales
    if max_permission == 1:
        return redirect('materials:materials_list')  
    if max_permission == 0:
        return redirect('dashboard')  # Página de no permiso si el usuario no tiene acceso para ver materiales
    
    if request.method == 'POST':
        form = MaterialForm(request.POST)
        if form.is_valid():
            material = form.save(commit=False)
            material.created_by = request.user
            material.save()
            return redirect('materials:materials_create') # Redirige al formulario vacío después de guardar
    else:
        form = MaterialForm()

    return render(request, 'materials/material_form.html', {'form': form})

@login_required
def material_edit(request, id):
    material = get_object_or_404(Material, pk=id)
    max_permission = UserRole.objects.filter(user_id=request.user).aggregate(max_permission=models.Max('role__materials'))['max_permission'] or 0

    # Verificamos si el usuario tiene permiso para crear o modificar materiales
    if max_permission == 1:
        return redirect('materials:materials_list') # Redirige a la lista de materiales si el usuario solo tiene permiso de vista 
    if max_permission == 0:
        return redirect('dashboard')  # Página de no permiso si el usuario no tiene acceso para ver materiales

    if request.method == 'POST':
        form = MaterialForm(request.POST, instance=material)
        if form.is_valid():
            form.save()
            return redirect('materials:materials_list')
    else:
        form = MaterialForm(instance=material)
        context = {
            'form': form,
            'material': material,
        }

    return render(request, 'materials/material_form.html', context)

@login_required
def material_delete(request, id):
    max_permission = UserRole.objects.filter(user_id=request.user).aggregate(max_permission=models.Max('role__materials'))['max_permission'] or 0

    # Verificamos si el usuario tiene permiso para crear o modificar materiales
    if max_permission < 2:
        return redirect('materials:materials_list') # Redirige a la lista de materiales si el usuario no tiene permiso para eliminar
    if max_permission == 0:
        return redirect('dashboard')  # Página de no permiso si el usuario no tiene acceso para ver materiales
    
    material = Material.objects.get(pk=id)
    if request.method == 'POST':
        material.delete()
        return redirect('materials:materials_list')
    
    return redirect('materials:materials_list')

app_materials/templates/materials/material_form.html
{% extends "core/base.html" %}

{% block title %}
{% if material %}Edit Material{% else %}Create Material{% endif %}
{% endblock title %}

{% block content %}

<h2 class="text-3xl font-bold text-gray-800 mb-6 border-b-2 border-gray-400 pb-2">Materials</h2>

<div class="max-w-xl mx-auto bg-white p-8 rounded-lg shadow-md mt-10">
    <h2 class="text-2xl font-bold text-gray-800 mb-6 border-b-2 border-gray-400 pb-2">{% if material %}Edit Material{% else %}Create New Material{% endif %}</h2>
    <form method="post" class="space-y-6">
        {% csrf_token %}
        {% if form.non_field_errors %}
        <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 mb-4 rounded" role="alert">
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <span class="text-sm text-red-600">{{ form.non_field_errors }}</span>
        <div class="space-y-4">
            <div class="flex items-center justify-between space-x-4">
                <label for="{{ form.id_material.id_for_label }}" class="block text-sm font-medium text-gray-700 w-1/3">Material ID:</label>
                <div class="mt-1 w-2/3">
                    <input type="text" name="{{ form.id_material.html_name }}" id="{{ form.id_material.id_for_label }}" value="{{ form.id_material.value | default:" "}}" class="w-full py-2 px-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#233b6e]"/>
                    {% if form.id_material.errors %}
                    <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-2 mt-1 rounded text-sm">
                        {{ form.id_material.errors }}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="flex items-center justify-between space-x-4">
                <label for="{{ form.name.id_for_label }}" class="block text-sm font-medium text-gray-700 w-1/3">Name:</label>
                <div class="mt-1 w-2/3">
                    <input type="text" name="{{ form.name.html_name }}" id="{{ form.name.id_for_label }}" value="{{ form.name.value | default:" "}}" class="w-full py-2 px-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#233b6e]"/>
                </div>
            </div>
            <div class="flex items-center justify-between space-x-4">
                <label for="{{ form.description.id_for_label }}" class="block text-sm font-medium text-gray-700 w-1/3">Description:</label>
                <div class="mt-1 w-2/3">
                    <input type="text" name="{{ form.description.html_name }}" id="{{ form.description.id_for_label }}" value="{{ form.description.value | default:" "}}" class="w-full py-2 px-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#233b6e]"/>
                </div>
            </div>
            <div class="flex items-center justify-between space-x-4">
                <label for="{{ form.unit.id_for_label }}" class="block text-sm font-medium text-gray-700 w-1/3">Unit:</label>
                <div class="mt-1 w-2/3">
                    <input type="text" name="{{ form.unit.html_name }}" id="{{ form.unit.id_for_label }}" value="{{ form.unit.value | default:" "}}" class="w-full py-2 px-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#233b6e]"/>
                </div>
            </div>
            <div class="flex items-center justify-between space-x-4">
                <label for="{{ form.material_type.id_for_label }}" class="block text-sm font-medium text-gray-700 w-1/3">Material type:</label>
                <div class="mt-1 w-2/3">
                    <input type="text" name="{{ form.material_type.html_name }}" id="{{ form.material_type.id_for_label }}" value="{{ form.material_type.value | default:" "}}" class="w-full py-2 px-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#233b6e]"/>
                </div>
            </div>
            <div class="flex items-center justify-between space-x-4">
                <label for="{{ form.status.id_for_label }}" class="block text-sm font-medium text-gray-700 w-1/3">Status:</label>
                <div class="mt-1 w-2/3">
                    <select name="{{ form.status.html_name }}" id="{{ form.status.id_for_label }}" class="w-full py-2 px-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#233b6e]"/>
                        <option value="Active" {%if form.status.value == 'Active' %}selected{% endif %}>Active</option>
                        <option value="Inactive" {%if form.status.value == 'Inactive' %}selected{% endif %}>Inactive</option>
                        <input type="hidden" name="{{ form.created_by.html_name }}" value="{{ user.username }}">
                    </select>
                </div>
            </div>
        </div>
        <div class="flex justify-end space-x-4">
            <a href="{% url 'materials:materials_list' %}" class="bg-blue-500 text-gray-800 font-semibold px-6 py-2 rounded-lg transition-colors duration-300 hover:bg-gray-400">Cancel</a>
            <button type="submit" class="bg-[#233b6e] text-white font-semibold px-6 py-2 rounded-lg transition-colors duration-300 hover:bg-[#1a2c53]">{% if material %}Edit{% else %}Create{% endif %}</button>
        </div>
    </form>
</div>

{% endblock content %}

app_materials/templates/materials/material_list.html
{% extends "core/base.html" %}

{% load static %}

{% block title %}Material{% endblock title %}

{% block content %}

<h2 class="text-3xl font-bold text-gray-800 mb-6 border-b-2 border-gray-400 pb-2">Materials</h2>
<div class="mb-6 p-4 border rounded-lg bg-gray-50">
    <form method="get" action="{% url 'materials:materials_list' %}" class="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
        <div class="col-span-1">
            <label for="id_material" class="block text-sm font-medium text-gray-700">ID Material</label>
            <input type="text" name="id_material" id="id_material" value="{{ request.GET.id_material }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-indigo-300 focus:ring-indigo-200 focus:ring-opacity-50">
        </div>
        <div class="col-span-1">
            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
            <input type="text" name="name" id="name" value="{{ request.GET.name }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-indigo-300 focus:ring-indigo-200 focus:ring-opacity-50">
        </div>
        <div class="col-span-1">
            <label for="material_type" class="block text-sm font-medium text-gray-700">Material Type</label>
            <input type="text" name="material_type" id="material_type" value="{{ request.GET.material_type }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-indigo-300 focus:ring-indigo-200 focus:ring-opacity-50">
        </div>
        <div class="col-span-1">
            <label for="status" class="block text-sm font-medium text-gray-700">Status</label>
            <select name="status" id="status" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-indigo-300 focus:ring-indigo-200 focus:ring-opacity-50">
                <option value="" {% if not request.GET.status %}selected{% endif %}>All</option>
                <option value="active" {% if request.GET.status == 'Active' %}selected{% endif %}>Active</option>
                <option value="inactive" {% if request.GET.status == 'Inactive' %}selected{% endif %}>Inactive</option>
            </select>
        </div>
        <!-- Buttons Section -->
        <div class="col-span-1 md:col-span-4">
            <div class="flex items-center justify-between">
                <div class="flex space-x-2">
                    <button type="submit" class="w-full md:w-auto bg-[#233b6e] text-white px-4 py-2 rounded-lg shadow-md hover:bg-[#1a2c53] transition-colors duration-300">Filter</button>
                    <a href="{% url 'materials:materials_list' %}" class="w-full md:w-auto bg-gray-500 text-white px-4 py-2 rounded-lg shadow-md hover:bg-gray-600 transition-colors duration-300 text-center">Clear</a>
                </div>
                <div class="flex items-center space-x-2 mt-4 md:mt-0">
                    <!-- Export buttons, nos lleva funcion CSV en views.py y tambien toma todos los valores que tengamos en el filtro -->
                    <a href="?export=csv{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" class="bg-green-600 text-white font-semibold px-6 py-2 rounded-lg shadow-md hover:bg-green-700 transition-colors duration-300 text-center">Export CSV</a>
                </div>
                {% if permissions.materials >= 2 %}
                <a href="{% url 'materials:materials_create' %}" class="bg-[#233b6e] text-white font-semibold px-6 py-2 rounded-lg text-center  transition-colors duration-300 hover:bg-[#1a2c53] ">Create New Material</a>
                {% endif %}
            </div>
        </div>
    </form>
</div>

<div class="bg-white p-6 rounded-lg shadow-md overflow-x-auto">
    <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
            <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ID Material</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Description</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Unit</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">User</th>
                {% if permissions.materials >= 2 %}
                <th scope="col" class="relative px-6 py-3">Actions</th>
                {% endif %}
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
            {% for material in pag_obj %}
            <tr>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ material.id_material }}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ material.name }}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ material.description }}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ material.unit }}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ material.material_type }}</td>
                <td class="px-6 py-4 whitespace-nowrap">
                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full {% if material.status == 'Active' %} bg-green-100 text-green-800{% else %}bg-red-100 text-red-800{% endif %}">
                        {{ material.status }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{{ material.created_by.username }}</td>
                {% if permissions.materials >= 2 %}
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <a href="{% url 'materials:material_edit' material.id %}" class="text-indigo-600 hover:text-indigo-900 mr-4">Edit</a>
                    <form method="post" action="{% url 'materials:material_delete' material.id %}" class="inline-block">
                        {% csrf_token %}
                        <button type="submit" class="text-red-600 hover:text-red-900 transition-colors duration-300" title="Delete" onclick="return confirm('Are you sure you want to delete this material?')">Delete</button>
                    </form>
                </td>
                {% endif %}
            </tr>
            {% empty %}
                <tr>
                    <td colspan="7" class="px-6 py-4 whitespace-nowrap text-sm text-center text-gray-500">No materials found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <!-- Pagination Controls - si hay mas paginas de resultados -->
    {% if pag_obj.has_other_pages %}
    <div class="flex justify-center mt-6">
        <nav class="relative z-0 inline-flex rounded-md shadow-sm -space-x-px" aria-label="Pagination">
            {% if pag_obj.has_previous %}
            <a href="?page=&id_material={{ request.GET.id_material }}&name={{ request.GET.name }}&material_type={{ request.GET.material_type }}&status={{ request.GET.status }}&page={{ pag_obj.previous_page_number }}" class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">
                <span class="sr-only">Previous</span>
                &lsaquo;
                <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M12.293 16.293a1 1 0 010-1.414L8.414 11l3.879-3.879a1 1 0 111.414 1.414l-4.586 4.586a1 1 0 01-1.414 0l-4.586-4.586a1 1 0 111.414-1.414L7.586 11l3.879 3.879a1 1 0 011.414 1.414z" clip-rule="evenodd" />
                </svg>
            </a>
            {% endif %}
            {% for i in pag_obj.paginator.page_range %}
                {% if pag_obj.number == i %}
                <span class="relative inline-flex items-center px-4 py-2 border border-gray-300 bg-gray-200 text-sm font-medium text-gray-700">{{ i }}</span>
                {% else %}
                <!-- Volvemos a pasar todos los parametros de filtrado actuales, esto para que cuando un usuario cambie de pagina sus filtros de busqueda permaneceran -->
                <a href="?page={{ i }}&id_material={{ request.GET.id_material }}&name={{ request.GET.name }}&material_type={{ request.GET.material_type }}&status={{ request.GET.status }}" class="realtive inline-flex items-center px-2 py-2 border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">{{ i }}</a>
                {% endif %}
            {% endfor %}
            {% if pag_obj.has_next %}
            <a href="?page=&id_material={{ request.GET.id_material }}&name={{ request.GET.name }}&material_type={{ request.GET.material_type }}&status={{ request.GET.status }}&page={{ pag_obj.next_page_number }}" class="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">
                <span class="sr-only">Next</span>
                &rsaquo;
                <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M7.707 16.293a1 1 0 010-1.414L11.586 11 7.707 7.121a1 1 0 111.414-1.414l4.586 4.586a1 1 0 010 1.414l-4.586 4.586a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                </svg>
            </a>
            <a href="?page=&id_material={{ request.GET.id_material }}&name={{ request.GET.name }}&material_type={{ request.GET.material_type }}&status={{ request.GET.status }}&page={{ pag_obj.paginator.num_pages }}" class="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 ml-2">
                <span class="sr-only">Last</span>
                &raquo;
            </a>
            {% endif %}
        </nav>
    </div>
    {% endif %}
</div>
{% endblock content %}