app_suppliers/urls.py
from django.urls import path
from app_suppliers import views

app_name = 'suppliers'

urlpatterns = [
    path('', views.suppliers_list, name='suppliers_list'),
    path('create/', views.supplier_create, name='supplier_create'),
    path('edit/<int:id>/', views.supplier_edit, name='supplier_edit'),
    path('delete/<int:id>/', views.supplier_delete, name='supplier_delete'),
]

erp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_users.urls')),
    path('', include('app_core.urls')),
    path('materials/', include(('app_materials.urls'), namespace='materials')),
    path('suppliers/', include(('app_suppliers.urls'), namespace='suppliers')),
]

app_suppliers/models.py
from django.conf import settings
from django.db import models

class Supplier(models.Model):
    id_supplier = models.CharField(max_length=50, unique=True, verbose_name="Supplier ID")
    legal_name = models.CharField(max_length=150, blank=True, verbose_name="Legal Name")
    name = models.CharField(max_length=150, verbose_name="Name")
    tax_id = models.CharField(max_length=30, verbose_name="Tax ID")
    country = models.CharField(max_length=60, verbose_name="Country")
    state_province = models.CharField(max_length=60, verbose_name="State/Province")
    city = models.CharField(max_length=100, verbose_name="City")
    address = models.CharField(max_length=150, verbose_name="Address")
    zip_code = models.IntegerField(verbose_name="ZIP Code")
    phone = models.IntegerField(verbose_name="Phone")
    email = models.EmailField(max_length=150, verbose_name="Email")
    contact_name = models.CharField(max_length=150, verbose_name="Contact Person")
    contact_role = models.CharField(max_length=150, verbose_name="Contact Role")
    category = models.CharField(max_length=150, verbose_name="Category")
    payment_terms = models.CharField(max_length=150, verbose_name="Payment Terms")
    currency = models.CharField(max_length=50, verbose_name="Currency")
    payment_method = models.CharField(max_length=100, verbose_name="Payment Method")
    bank_account = models.CharField(max_length=150, verbose_name="Bank Account")

    status = models.CharField(max_length=50, verbose_name="Status")

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name="Created by", related_name="suppliers_created") # Usuario que este logueado y que creó el registro, se usa SET_NULL para no eliminar el proveedor si el usuario es eliminado, y se completará automaticamente al crear el registro
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name="Updated by", related_name="suppliers_updated") # Usuario que este logueado y que actualizó el registro
    class Meta:
        db_table = 'suppliers'
        verbose_name = 'Supplier'
        verbose_name_plural = 'Suppliers'
        ordering = ['name']

    def __str__(self):
        return self.name

app_suppliers/forms.py
from django import forms

from app_suppliers.models import Supplier

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ['id_supplier','legal_name', 'name', 'tax_id', 'country', 'state_province', 'city', 'address', 'zip_code', 'phone', 'email', 'contact_name', 'contact_role', 'category', 'payment_terms', 'currency', 'payment_method', 'bank_account', 'status']

app_suppliers/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.db import models
from app_suppliers.forms import SupplierForm
from app_users.models import UserRole
from app_suppliers.models import Supplier
import csv


@login_required
def suppliers_list(request):

    result = UserRole.objects.filter(user_id=request.user).aggregate(max_permission=models.Max('role__suppliers'))
    
    max_permission = result['max_permission'] or 0

    if max_permission == 0:
        return redirect('dashboard')  # Página de no permiso si el usuario no tiene acceso para ver materiales
   
    # Lógica para obtener la lista de provedores
    supplier_list = Supplier.objects.all()
    
    id_supplier = request.GET.get('id_supplier')
    name = request.GET.get('name')
    country = request.GET.get('country')
    status = request.GET.get('status')

    if id_supplier:
        supplier_list = supplier_list.filter(id_supplier__icontains=id_supplier)
    if name:
        supplier_list = supplier_list.filter(name__icontains=name)
    if country:
        supplier_list = supplier_list.filter(country__icontains=country)
    if status is not None and status != '':
        supplier_list = supplier_list.filter(status=status)

    # Exportar a CSV si se solicita
    if request.GET.get('export') == 'csv':
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="suppliers.csv"'
        response.write('\ufeff'.encode('utf8'))  # BOM para Excel

        writer = csv.writer(response)
        writer.writerow(['ID Supplier', 'Legal Name', 'Name', 'Tax ID', 'Country', 'State/Province', 'City', 'Address', 'Zip Code', 'Phone', 'Email', 'Contact name', ' Contact role', 'Category', 'Payment terms', 'Currency', 'Payment method', 'Bank Account', 'Status', 'Created By', 'Created At', 'Updated At'])
        for supplier in supplier_list:
            writer.writerow([
                supplier.id_supplier, 
                supplier.legal_name, 
                supplier.name, 
                supplier.tax_id, 
                supplier.country, 
                supplier.state_province, 
                supplier.city,
                supplier.address,
                supplier.zip_code,
                supplier.phone,
                supplier.email,
                supplier.contact_name,
                supplier.contact_role,
                supplier.category,
                supplier.payment_terms,
                supplier.currency,
                supplier.payment_method,
                supplier.bank_account,
                supplier.status, 
                supplier.created_by.username if supplier.created_by else 'N/A', 
                supplier.created_at.strftime('%Y-%m-%d %H:%M:%S'), 
                supplier.updated_at.strftime('%Y-%m-%d %H:%M:%S')])
        return response

    paginator = Paginator(supplier_list, 10)  # 10 proveedores por página
    page_number = request.GET.get('page')
    pag_obj = paginator.get_page(page_number)

    return render(request, 'suppliers/supplier_list.html', {'pag_obj': pag_obj})


def supplier_create(request):
    max_permission = UserRole.objects.filter(user_id=request.user).aggregate(max_permission=models.Max('role__suppliers'))['max_permission'] or 0

    # Verificamos si el usuario tiene permiso para crear o modificar proveedores
    if max_permission == 1:
        return redirect('suppliers:suppliers_list')  
    if max_permission == 0:
        return redirect('dashboard')  # Página de no permiso si el usuario no tiene acceso para ver proveedores
    
    if request.method == 'POST':
        form = SupplierForm(request.POST)
        if form.is_valid():
            supplier = form.save(commit=False)
            supplier.created_by = request.user
            supplier.save()
            return redirect('suppliers:suppliers_create') # Redirige al formulario vacío después de guardar
    else:
        form = SupplierForm()

    return render(request, 'suppliers/supplier_form.html', {'form': form})

@login_required
def supplier_edit(request, id):
    supplier = get_object_or_404(Supplier, pk=id)
    result = UserRole.objects.filter(user_id=request.user).aggregate(max_permission=models.Max('role__materials'))
    
    max_permission = result['max_permission'] or 0

    # Verificamos si el usuario tiene permiso para crear o modificar proveedores
    if max_permission == 1:
        return redirect('suppliers:suppliers_list') # Redirige a la lista de proveedores si el usuario solo tiene permiso de vista 
    if max_permission == 0:
        return redirect('dashboard')  # Página de no permiso si el usuario no tiene acceso para ver proveedores
    if request.method == 'POST':
        form = SupplierForm(request.POST, instance=supplier)
        if form.is_valid():
            form.save()
            return redirect('suppliers:suppliers_list')
    else:
        form = SupplierForm(instance=supplier)
        context = {
            'form': form,
            'supplier': supplier,
        }

    return render(request, 'suppliers/supplier_form.html', context)

@login_required
def supplier_delete(request, id):
    result = UserRole.objects.filter(user_id=request.user).aggregate(max_permission=models.Max('role__suppliers'))
    max_permission = result['max_permission'] or 0

    # Verificamos si el usuario tiene permiso para crear o modificar proveedores
    if max_permission < 2:
        return redirect('suppliers:suppliers_list') # Redirige a la lista de proveedores si el usuario no tiene permiso para eliminar
    if max_permission == 0:
        return redirect('dashboard')  # Página de no permiso si el usuario no tiene acceso para ver proveedores
    
    supplier = Supplier.objects.get(pk=id)
    if request.method == 'POST':
        supplier.delete()
        return redirect('suppliers:suppliers_list')
    
    return redirect('suppliers:suppliers_list')

app_suppliers/templates/suppliers/supplier_list.html
{% extends "core/base.html" %}

{% load static %}

{% block title %}Suppliers{% endblock title %}

{% block content %}

<h2 class="text-3xl font-bold text-gray-800 mb-6 border-b-2 border-gray-400 pb-2">Suppliers</h2>
<div class="mb-6 p-4 border rounded-lg bg-gray-50">
    <form method="get" action="{% url 'suppliers:suppliers_list' %}" class="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
        <div class="col-span-1">
            <label for="id_supplier" class="block text-sm font-medium text-gray-700">ID Supplier</label>
            <input type="text" name="id_supplier" id="id_supplier" value="{{ request.GET.id_supplier }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-indigo-300 focus:ring-indigo-200 focus:ring-opacity-50">
        </div>
        <div class="col-span-1">
            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
            <input type="text" name="name" id="name" value="{{ request.GET.name }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-indigo-300 focus:ring-indigo-200 focus:ring-opacity-50">
        </div>
        <div class="col-span-1">
            <label for="country" class="block text-sm font-medium text-gray-700">Country</label>
            <input type="text" name="country" id="country" value="{{ request.GET.country }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-indigo-300 focus:ring-indigo-200 focus:ring-opacity-50">
        </div>
        <div class="col-span-1">
            <label for="status" class="block text-sm font-medium text-gray-700">Status</label>
            <select name="status" id="status" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-indigo-300 focus:ring-indigo-200 focus:ring-opacity-50">
                <option value="" {% if not request.GET.status %}selected{% endif %}>All</option>
                <option value="Active" {% if request.GET.status == 'Active' %}selected{% endif %}>Active</option>
                <option value="Inactive" {% if request.GET.status == 'Inactive' %}selected{% endif %}>Inactive</option>
            </select>
        </div>
        <!-- Buttons Section -->
        <div class="col-span-1 md:col-span-4">
            <div class="flex items-center justify-between">
                <div class="flex space-x-2">
                    <button type="submit" class="w-full md:w-auto bg-[#233b6e] text-white px-4 py-2 rounded-lg shadow-md hover:bg-[#1a2c53] transition-colors duration-300">Filter</button>
                    <a href="{% url 'suppliers:suppliers_list' %}" class="w-full md:w-auto bg-gray-500 text-white px-4 py-2 rounded-lg shadow-md hover:bg-gray-600 transition-colors duration-300 text-center">Clear</a>
                </div>
                <div class="flex items-center space-x-2 mt-4 md:mt-0">
                    <!-- Export buttons, nos lleva funcion CSV en views.py y tambien toma todos los valores que tengamos en el filtro -->
                    <a href="?export=csv{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" class="bg-green-600 text-white font-semibold px-6 py-2 rounded-lg shadow-md hover:bg-green-700 transition-colors duration-300 text-center">Export CSV</a>
                </div>
                {% if permissions.suppliers >= 2 %}
                <a href="{% url 'suppliers:supplier_create' %}" class="bg-[#233b6e] text-white font-semibold px-6 py-2 rounded-lg text-center  transition-colors duration-300 hover:bg-[#1a2c53] ">Create New Supplier</a>
                {% endif %}
            </div>
        </div>
    </form>
</div>

<div class="bg-white p-6 rounded-lg shadow-md overflow-x-auto">
    <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
            <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ID Supplier</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Country</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Category</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">User</th>
                {% if permissions.suppliers >= 2 %}
                <th scope="col" class="relative px-6 py-3">Actions</th>
                {% endif %}
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
            {% for supplier in pag_obj %}
            <tr>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ supplier.id_supplier }}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ supplier.name }}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ supplier.country }}</td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ supplier.category }}</td>
                <td class="px-6 py-4 whitespace-nowrap">
                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full {% if supplier.status == 'Active' %} bg-green-100 text-green-800{% else %}bg-red-100 text-red-800{% endif %}">
                        {{ supplier.status }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{{ supplier.created_by.username }}</td>
                {% if permissions.suppliers >= 2 %}
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <a href="{% url 'suppliers:supplier_edit' supplier.id %}" class="text-indigo-600 hover:text-indigo-900 mr-4">Edit</a>
                    <form method="post" action="{% url 'suppliers:supplier_delete' supplier.id %}" class="inline-block">
                        {% csrf_token %}
                        <button type="submit" class="text-red-600 hover:text-red-900 transition-colors duration-300" title="Delete" onclick="return confirm('Are you sure you want to delete this supplier?')">Delete</button>
                    </form>
                </td>
                {% endif %}
            </tr>
            {% empty %}
                <tr>
                    <td colspan="7" class="px-6 py-4 whitespace-nowrap text-sm text-center text-gray-500">No suppliers found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <!-- Pagination Controls - si hay mas paginas de resultados -->
    {% if pag_obj.has_other_pages %}
    <div class="flex justify-center mt-6">
        <nav class="relative z-0 inline-flex rounded-md shadow-sm -space-x-px" aria-label="Pagination">
            {% if pag_obj.has_previous %}
            <a href="?page=&id_supplier={{ request.GET.id_supplier }}&name={{ request.GET.name }}&supplier_type={{ request.GET.supplier_type }}&status={{ request.GET.status }}&page={{ pag_obj.previous_page_number }}" class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">
                <span class="sr-only">Previous</span>
                &lsaquo;
                <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M12.293 16.293a1 1 0 010-1.414L8.414 11l3.879-3.879a1 1 0 111.414 1.414l-4.586 4.586a1 1 0 01-1.414 0l-4.586-4.586a1 1 0 111.414-1.414L7.586 11l3.879 3.879a1 1 0 011.414 1.414z" clip-rule="evenodd" />
                </svg>
            </a>
            {% endif %}
            {% for i in pag_obj.paginator.page_range %}
                {% if pag_obj.number == i %}
                <span class="relative inline-flex items-center px-4 py-2 border border-gray-300 bg-gray-200 text-sm font-medium text-gray-700">{{ i }}</span>
                {% else %}
                <!-- Volvemos a pasar todos los parametros de filtrado actuales, esto para que cuando un usuario cambie de pagina sus filtros de busqueda permaneceran -->
                <a href="?page={{ i }}&id_supplier={{ request.GET.id_supplier }}&name={{ request.GET.name }}&supplier_type={{ request.GET.supplier_type }}&status={{ request.GET.status }}" class="realtive inline-flex items-center px-2 py-2 border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">{{ i }}</a>
                {% endif %}
            {% endfor %}
            {% if pag_obj.has_next %}
            <a href="?page=&id_supplier={{ request.GET.id_supplier }}&name={{ request.GET.name }}&supplier_type={{ request.GET.supplier_type }}&status={{ request.GET.status }}&page={{ pag_obj.next_page_number }}" class="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">
                <span class="sr-only">Next</span>
                &rsaquo;
                <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M7.707 16.293a1 1 0 010-1.414L11.586 11 7.707 7.121a1 1 0 111.414-1.414l4.586 4.586a1 1 0 010 1.414l-4.586 4.586a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                </svg>
            </a>
            <a href="?page=&id_supplier={{ request.GET.id_supplier }}&name={{ request.GET.name }}&supplier_type={{ request.GET.supplier_type }}&status={{ request.GET.status }}&page={{ pag_obj.paginator.num_pages }}" class="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 ml-2">
                <span class="sr-only">Last</span>
                &raquo;
            </a>
            {% endif %}
        </nav>
    </div>
    {% endif %}
</div>
{% endblock content %}